/*
 * VeriWaveX - Professional Verilog Simulation Suite
 * Version: 2.0.0 (Linux/Windows Cross-Platform)
 * Copyright (c) 2026 Aritrash Sarkar. All Rights Reserved.
 * Unauthorized copying of this file, via any medium is strictly prohibited.
 * Proprietary and confidential.
 * Written by Aritrash Sarkar <aritrashsarkar@gmail.com>, April 2026
 */

#![windows_subsystem = "windows"]

// --- 1. MODULE DECLARATIONS ---
mod models;
mod logic;
mod app;
mod ui;

use eframe::egui;

fn main() -> eframe::Result<()> {
    // --- 2. ICON LOADING ---
    // Loading the app icon from the assets folder. 
    // Ensure 'image' crate is in Cargo.toml with "png" feature.
    let icon_bytes = include_bytes!("../assets/logo.png");
    let icon = image::load_from_memory(icon_bytes).ok().map(|img| {
        let rgba = img.to_rgba8();
        let (width, height) = rgba.dimensions();
        egui::IconData {
            rgba: rgba.into_raw(),
            width,
            height,
        }
    });

    // --- 3. NATIVE OPTIONS ---
    let options = eframe::NativeOptions {
        viewport: egui::ViewportBuilder::default()
            .with_maximized(true)
            .with_inner_size([1200.0, 800.0])
            .with_icon(icon.unwrap_or_default()),
        ..Default::default()
    };

    // --- 4. EXECUTION ---
    eframe::run_native(
        "VeriWaveX v2.0.0",
        options,
        Box::new(|cc| {
            // CRITICAL: This enables egui to render the PNG schematics 
            // generated by Yosys and Graphviz.
            egui_extras::install_image_loaders(&cc.egui_ctx);
            
            // Initialize the modular app state
            Ok(Box::new(app::VerilogApp::new(cc)))
        }),
    )
}